apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter
spec:
  attachMetadata:
    node: false
  endpoints:
  - port: http-metrics
    scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/name: node-exporter
