groups:
- name: global.rules
  rules:
  - alert: TargetMissing
    expr: up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Missing target to monitor: (instance {{ $labels.instance }})"
      description: "A prometheus target has gone missing, please investigate"
