apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-retained
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  dataLocality: "disabled"
  fromBackup: ""
  fsType: "ext4"
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
  unmapMarkSnapChainRemoved: "ignored"
