{
 "title": "Node Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "query": {
     "query": "label_values(node_boot_time_seconds,node)"
    }
   },
   {
    "name": "network_device",
    "query": {
     "query": "label_values(node_network_device_id{node=~\"$node\", device=~\"eth.*|ens.*|cni.*|flannel.*\"},device)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (min by (node) (irate(node_cpu_seconds_total{mode=\"idle\", node=~\"$node\"}[5m])))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "RAM Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1- (node_memory_MemAvailable_bytes{node=~\"$node\"} / node_memory_MemTotal_bytes{node=~\"$node\"})",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Disk R/W",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (node) (irate(node_disk_read_bytes_total{node=~\"$node\"}[5m]))",
     "legendFormat": "{{ node }} - read"
    },
    {
     "expr": "sum by (node) (irate(node_disk_written_bytes_total{node=~\"$node\"}[5m]))",
     "legendFormat": "{{ node }} - write"
    }
   ]
  },
  {
   "title": "Disk FREE (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{fstype=\"ext4\", node=~\"$node\"} / node_filesystem_size_bytes{fstype=\"ext4\", node=~\"$node\"}",
     "legendFormat": "{{ node }} - {{ device }}"
    }
   ]
  },
  {
   "title": "Load Average [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node_load5{node=~\"$node\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "inode Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - node_filesystem_files_free{fstype=\"ext4\", node=~\"$node\"} / node_filesystem_files{fstype=\"ext4\", node=~\"$node\"}",
     "legendFormat": "{{ node }}/{{ device }}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device=~\"$network_device\", node=~\"$node\"}[10m])",
     "legendFormat": "{{ node }}/{{ device }} - rcv"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device=~\"$network_device\", node=~\"$node\"}[10m])",
     "legendFormat": "{{ node }}/{{ device }} - trn"
    }
   ]
  },
  {
   "title": "Dropped Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_drop_total{device=~\"(eth0|ens3)\", node=~\"$node\"}[5m])) by (node, device)",
     "legendFormat": "{{ node }}/{{ device }} - rcv"
    },
    {
     "expr": "sum(irate(node_network_transmit_drop_total{device=~\"(eth0|ens3)\", node=~\"$node\"}[5m])) by (node, device)",
     "legendFormat": "{{ node }}/{{ device }} - trn"
    }
   ]
  }
 ]
}