resources:
  - ../../base/monitoring

patches:
  - target:
      kind: HelmChart
      name: kube-prometheus-stack
    patch: |-
      - op: add
        path: /spec/set
        value:
          grafana.ingress.enabled: "true"
          grafana.ingress.hosts[0]: grafana.example.com
          prometheus.ingress.enabled: "true"
          prometheus.ingress.hosts[0]: prometheus.example.com
