resources:
  - ../../base/longhorn
  - ../../base/monitoring

patches:
  # monitoring
  - target:
      kind: Ingress
      name: prometheus
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: example.com
  - target:
      kind: Ingress
      name: grafana
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: example.com
  # longhorn
  - target:
      kind: HelmChart
      name: longhorn
    patch: |-
      - op: add
        path: /spec/set
        value:
          ingress.enabled: "true"
          ingress.host: example.com
