name: Release
on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      repo: ghcr.io/octarect/ops
      context_path: ./docker/ops
    steps:
      - uses: actions/checkout@v2

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.repo }}
          tags: |
            type=raw,value=latest,enable={{ is_default_branch }}
            type=raw,value={{ date 'YYYY-MM-DD' }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.context_path }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
